### ISSUE TITLE
Darker background on certain words

### ISSUE THREAD

**Issue by crockett95** [altercation/vim-colors-solarized#100]
Forgive me if this is a dumb question, but I'm new to vim. When I added the solarized dark theme, vim is changing the background color on certain words, e.g. parentheses on php function calls and arguments within those calls. How can I make it not do that?

**Comment by oryband** [comment]
It looks like this repo is no longer being maintained. There are several forks which might fix your problem. You can try [looking in here](http://forked.yannick.io/altercation/vim-colors-solarized) for the most popular or updated ones.

**Comment by Patagonicus** [comment]
In case anyone stumbles upon this because (s)he has the same problem just like I did:

For me this was fixed by setting g:solarized_termtrans to 1. The readme says that this is for transparency but basically it just switches from using base03 explicetly to using "NONE" (= terminal default) as the background color.
