### ISSUE TITLE
Certain CSS keywords  are almost invisible

### ISSUE THREAD

**Issue by mnazim** [altercation/vim-colors-solarized#8]
CSS keywords like _float, center, right, left_ are almost invisible. See the screenshot.

![Solarized CSS Screenshot](http://dl.dropbox.com/u/12665171/solarized-css-color-bug.png)

Problem persists both in dark and light schemes.

**Comment by altercation** [comment]
What's the output of `:set filetype` on that file? Plain jane css?

Also, are you using any particular css syntax plugin? In the default css syntax there is no differentiation between the value and unit type (both are cssValueLength).

I suspect it's either using a different filetype that handles css that I don't know about or is a custom css syntax highlighting plugin. Can you check?

**Comment by mnazim** [comment]
FileType is set properly to css. 

I am using a Better Css Syntax pluging (https://github.com/ChrisYip/Better-CSS-Syntax-for-Vim)

Yes, I found out that if I disable the syntax plugin it works fine.

**Comment by altercation** [comment]
I'll look into what groups that syntax is referencing and see if I can massage it a bit.

**Comment by mnazim** [comment]
Just did an update and looks like it has been fixed.

**Comment by altercation** [comment]
See: https://github.com/altercation/solarized/issues/32

Looks like it's actually using Special and/or Non-text values. I could dig into it more but it's essentially fixed in the current solarized.vim code availble from the repo. Anyone else having this problem, please pull/clone and you'll have a more readable experience with bettercss.
